---
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /tmp/mongodata:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  user-registration:
    image: t0b9/user-registration:0.0.1
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_URI: mongodb://root:example@mongo:27017/knverse
